language: objective-c

osx_image: xcode7.3

before_install:
    - rvm use system
    - sudo gem install cocoapods -v '0.39.0'

script:
    xctool -workspace Tubulus.xcworkspace -scheme Tubulus build -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    xctool test -workspace Tubulus.xcworkspace -scheme TubulusTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO