language: objective-c

osx_image: xcode7.3

before_install:
	rvm install 2.2.5
	sudo gem install cocoapods

script:
	xctool -workspace Tubulus.xcworkspace -scheme Tubulus -sdk iphonesimulator build test